
- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        #category_names: ['SecurityUpdates']
      register: result

    # output results
    - debug: var=result

    # reboot only if required
    - win_reboot:
      when: result.reboot_required

    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present
  
    - name: Install Java
      windows.win_package:
        path: http://10.5.1.100/ISO/Software/java/jre-8u301-windows-i586.exe
        state: present
 
    - name: Install Kitty
      windows.win_package:
        path: http://10.5.1.100/ISO/Software/kitty/kitty-0.74.4.13.exe
        state: present
 
    - name: Install mRemote
      windows.win_package:
        path: http://10.5.1.100/ISO/Software/mRemote/mRemoteNG-Installer-1.77.1.27654.msi
        state: present

    - name: Install Wireshark
      windows.win_package:
        path: http://10.5.1.100/ISO/Software/Wireshark/Wireshark-win64-3.4.9.exe
        state: present
    
    - name: Install MobaXterm
      windows.win_package:
        path: http://10.5.1.100/ISO/Software/MobaXterm/MobaXterm_installer_21.3.msi
        state: present
        
    - name: Install Notepad plus plus
      windows.win_package:
        path: http://10.5.1.100/ISO/Software/notepad++/npp.8.1.5.Installer.x64.exe
        state: present

    - name: Install WinSCP
      windows.win_package:
        path: http://10.5.1.100/ISO/Software/winscp/WinSCP-5.19.2-Setup.exe
        state: present
